### ISSUE TITLE
Increase AWS EC2 vCPU Limit

### ISSUE THREAD

**Issue by ericpassmore** [eosnetworkfoundation/chicken-dance#93]
An error occurred (VcpuLimitExceeded) when calling the RunInstances operation: You have requested more vCPU capacity than your current vCPU limit of 770 allows for the instance bucket that the specified instance type belongs .
http://aws.amazon.com/contact-us/ec2-request

Can allocate 24 hosts today. Want to allocate 100+ so limit should go up 6x.

**Comment by kj4ezj** [comment]
![chickens-prod - increase EC2 instance service limit - AWS reply](https://github.com/eosnetworkfoundation/replay-test/assets/34947245/18e90155-7412-4e15-8478-13c793eac20a)

**Comment by kj4ezj** [comment]
AWS has partially increased our limit.

![AWS closing summary](https://github.com/eosnetworkfoundation/chicken-dance/assets/34947245/ab1b8c7d-ec93-4028-bc25-5f002c96bf69)

Is this acceptable for now @ericpassmore, or would you like me to being an appeal?

**Comment by ericpassmore** [comment]
This is good, and will close the ticket. Originally the requirements were to run in 3 hours ; however we haven't had requests to run this often.
